spring.application.name=gpugrid

spring.datasource.url=jdbc:postgresql://localhost:5432/gpugrid
spring.datasource.username=gpugrid
spring.datasource.password=${DB_PASSWORD:shreya}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true